first task, fetch without Relay
dimaspaiva/relay-workshop pull request #1
Opened 2020-08-31 21:27 UTC by dimaspaiva

2020-08-31 21:32 UTC, DaniloOliveira28 approved these changes

2020-08-31 21:34 UTC, BigsonLvrocha requested changes

2020-08-31 21:34 UTC, BigsonLvrocha commented on workshop/01-fetchGraphql/src/App.tsx
> +        query,
pode colocar uma propriedade "variables" para passar os argumentos de fist, after, last e before

2020-08-31 21:34 UTC, BigsonLvrocha commented on workshop/01-fetchGraphql/src/App.tsx
> +    query getPosts ${nextPage ? queryVars.declare : ''} {
```graphql
query getPosts( $first: Int, $last: Int, $after: String, $before: String ) {
  post(first: $first, after: $after, before: $before, last: $last) {
    [...]
  }
}

2020-08-31 21:34 UTC, BigsonLvrocha commented on workshop/01-fetchGraphql/src/App.tsx
> +        query,
```javascript
body: JSON.stringify({
        query,
        variables
})

2020-08-31 21:34 UTC, BigsonLvrocha commented on workshop/01-fetchGraphql/src/App.tsx
> +      {nextPage && <Button onClick={() => handleRequestPosts('before')}>Prev</Button>}
before

2020-09-01 18:22 UTC, BigsonLvrocha approved these changes

2020-09-01 18:25 UTC, merged